site_name: Godot 4.5 Lessons
site_url: https://YOUR_USERNAME.github.io/godot-lessons/
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - attr_list               # add attributes to markdown elements  
  - admonition              # notes, warnings, etc.
  - pymdownx.details        # collapsible sections
  - pymdownx.highlight:      
      use_pygments: true
      noclasses: false      
      #pygments_lang_class: true
      #auto_title: true
      anchor_linenums: true
      #linenums: true      
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.keys             # keyboard keys
  - pymdownx.superfences      # nested fenced code blocks
  - pymdownx.tabbed:          # tabbed content
      alternate_style: true   # optional, Material-style tabs
  - tables

plugins:
  - search 
  - macros 
  - custom_lexer

extra_css:
  - stylesheets/godot/test.css  
extra_javascript: []

nav:
  - Home: index.md
  - Lessons:      
      - Scene Mangement: lessons/scene_management.md
      - Autoloads: lessons/autoloads.md
      - Resources: lessons/resources.md
      - Input: lessons/input.md
      - Mouse Interactions: 
          - Mouse Interactions: lessons/mouse_interactions.md
          - Mouse Interactions Area3D: lessons/mouse_area3d.md
          - Mouse Interactions Raycast: lessons/mouse_raycast.md
      - Animation: lessons/animation.md
      - Lighting: lessons/lighting.md
      #- CSS Testing: others/gdscript_test.md
